all:
	echo "type *make clean* to delete temporary files"
clean: clean_files clean_directories custom
clean_files:
	rm -f config.yaml multiqc_config.yaml cluster_config.json slurm*out stats.txt unlock.sh schema.yaml nanomerge.sh nanomerge.rules ./Makefile
clean_directories:
	rm -rf .snakemake
custom:
	
